CREATE TABLE tarjetas(
ID INT PRIMARY KEY AUTO_INCREMENT,
PASION VARCHAR(255),
SALARIO_MINIMO DOUBLE,
SALARIO_MAXIMO DOUBLE,
EDAD_MINIMA INTEGER,
EDAD_MAXIMA INTEGER,
NOMBRE_TARJETA VARCHAR(255),
FECHA_ALTA DATE,
FECHA_MODIFICACION DATE
);